.onLoad <- function (libname, pkgname)
{
  # make data set names global to avoid CHECK notes
  utils::globalVariables ("Var1")
  utils::globalVariables ("Var2")
  utils::globalVariables ("variable")
  utils::globalVariables ("Observations")
  utils::globalVariables ("value")
  utils::globalVariables ("Method")
  utils::globalVariables ("Pattern")
  utils::globalVariables ("Comp_time")
  utils::globalVariables ("MCAR_RMSE")
  utils::globalVariables ("MAR_RMSE")
  utils::globalVariables ("MNAR_RMSE")
  utils::globalVariables ("MAP_RMSE")
  utils::globalVariables ("MCAR_MAE")
  utils::globalVariables ("MAR_MAE")
  utils::globalVariables ("MNAR_MAE")
  utils::globalVariables ("MAP_MAE")
  utils::globalVariables ("MCAR_KS")
  utils::globalVariables ("MAR_KS")
  utils::globalVariables ("MNAR_KS")
  utils::globalVariables ("MAP_KS")
  utils::globalVariables ("x")
  utils::globalVariables ("var1")
  utils::globalVariables ("imp.lo.ci")
  utils::globalVariables ("imp.hi.ci")
  utils::globalVariables ("orig.lo.ci")
  utils::globalVariables ("orig.hi.ci")
  utils::globalVariables ("orig.cor")
  utils::globalVariables ("imp.cor")

  invisible ()
}
