#' @title Testing the median imputation algorithm
#'
#' @description
#' \code{\link{test_median_imp}} tests the imputation accuracy of the median imputation algorithm on matrices with various missing data patterns
#'
#' @details
#' This function tests the imputation accuracy of the median imputation algorithm by comparing the
#' original simulated matrix with no missingess and the imputed matrices generated by the algorithm using the matrices with
#' MCAR, MAR, MNAR and (optionally) MAP missingness patterns. The function calculates root-mean-square error (RMSE)
#' between the imputed datapoints and the original datapoints (that were subsequently set to missing). The function will
#' automatically detect whether there is a MAP matrix in the list and calculate RMSE for all matrices provided in the list.
#'
#' @param X_hat Simulated matrix with no missingess (this matrix will be used to obtain the error between the original and imputed values). (Simulated_matrix output from the \code{\link{simulate}} function)
#' @param list List of matrices with various missingness patterns (MCAR, MAR, MNAR and optionally, MAP). (The input is ideally the R object that was generated using the \code{\link{all_patterns}} function)
#'
#' @name test_median_imp
#'
#' @inherit test_AmeliaII return
#'
#' @examples
#' \dontrun{
#' test_median_imp(X_hat = simulated$Simulated_matrix, list = miss_list)
#' }
#'
#' @export


# FUNCTION
test_median_imp <- function(X_hat, list) {
    
    index <- lapply(list, is.na)
    
    median_imp <- function(X) {
        for (i in 1:ncol(X)) {
            X[is.na(X[, i]), i] <- stats::median(X[, i], na.rm = TRUE)
        }
        
        list(Imputed = X)
    }
    
    results <- lapply(list, median_imp)
    
    # using NA index to identify the original values (later set to missing)
    orig_MCAR <- X_hat[index[[1]]]
    orig_MAR <- X_hat[index[[2]]]
    orig_MNAR <- X_hat[index[[3]]]
    if (length(index) == 4) 
        orig_MAP <- X_hat[index[[4]]]
    
    # using NA index to identify the imputed values
    imp_MCAR <- results$MCAR_matrix$Imputed[index[[1]]]
    imp_MAR <- results$MAR_matrix$Imputed[index[[2]]]
    imp_MNAR <- results$MNAR_matrix$Imputed[index[[3]]]
    if (length(index) == 4) 
        imp_MAP <- results$MAP_matrix$Imputed[index[[4]]]
    
    # RMSE
    rmse_MCAR <- sqrt(mean((orig_MCAR - imp_MCAR)^2))
    rmse_MAR <- sqrt(mean((orig_MAR - imp_MAR)^2))
    rmse_MNAR <- sqrt(mean((orig_MNAR - imp_MNAR)^2))
    if (length(index) == 4) 
        rmse_MAP <- sqrt(mean((orig_MAP - imp_MAP)^2))
    
    if (length(index) == 4) 
        list(MCAR_RMSE = rmse_MCAR, MAR_RMSE = rmse_MAR, MNAR_RMSE = rmse_MNAR, MAP_RMSE = rmse_MAP) else list(MCAR_RMSE = rmse_MCAR, MAR_RMSE = rmse_MAR, MNAR_RMSE = rmse_MNAR)
    
}



# LAB res <- dimple_all_patterns(yy$Simulated_matrix, y$Fraction_missingness_per_variable) res
# <- dimple_all_patterns(yy$Simulated_matrix, y$Fraction_missingness_per_variable,
# assumed_pattern = c('MAR', 'MCAR', 'MCAR', 'MAR', 'MNAR', 'MCAR', 'MAR', 'MAR', 'MNAR',
# 'MNAR'))

# xxzz <- test_median_imp(X_hat = yy$Simulated_matrix, list = res)
